// code pour overpass turbo: 

/*
This has been generated by the overpass-turbo wizard.
The original search was:
“landuse = residential”

[out:json][timeout:25];
// gather results
(
  // query part for: “landuse=residential”
  node["landuse"]({{bbox}});
  way["landuse"]({{bbox}});
  relation["landuse"]({{bbox}});
  way["sidewalk:left"]({{bbox}});
  way["sidewalk:right"]({{bbox}});
  way["sidewalk"]({{bbox}});
  way["sidewalk:both"]({{bbox}});
  way["maxspeed"]({{bbox}});
  node["public_transport"]({{bbox}});
  way["highway"]({{bbox}});
  node["amenity"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
*/